name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  platformio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build ESP32-C3 firmware
        run: pio run
